services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:16-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: password
    volumes:
      - redis:/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
      NODE_ENV: production
    command: >
      sh -c "pnpm db:migrate && pnpm db:seed"

  homechef:
    image: homechef:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - migrate
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_ROOT_DOMAIN: homechef:3000
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
      REDIS_URL: redis://:password@redis:6379
      RESEND_API_KEY: XXX
      RESEND_EMAIL_FROM: email@provider.com
    volumes:
      - homechef:/data

volumes:
  postgres:
  redis:
  homechef:
