export type RecipeDifficulty =
  | "beginner"
  | "easy"
  | "moderate"
  | "hard"
  | "expert"

export type KitchenToolCategory =
  | "paring knife"
  | "chef's knife"
  | "cutting board"
  | "measuring cups and spoons"
  | "kitchen shears"
  | "colander"
  | "can opener"
  | "mixing bowls"
  | "blender"
  | "grater"
  | "whisk"
  | "vegetable peeler"
  | "rolling pin"
  | "food processor"
  | "food scale"
  | "spatula"
  | "saucepan"
  | "sauté pan"
  | "skillet"
  | "baking sheet"
  | "oven mits"
  | "roasting pan"
  | "dutch oven"
  | "cooling rack"
  | "grill pan"
  | "potato masher"
  | "wok"
  | "meat thermometer"
  | "flatware"
  | "plates"
  | "bowls"
  | "glasses"
  | "glasses"
  | "mugs"
  | "salad bowl"
  | "serving bowl"
  | "serving plates"
  | "serving spoons"
  | "tongs"
  | "wine opener"
  | "pitcher"
  | "food storage containers"
  | "french press"
  | "teakettle"
  | "immersion blender"
  | "stand mixer"
  | "apron"
  | "parchment paper"

export type RecipeTag =
  | "spring"
  | "summer"
  | "fall"
  | "winter"
  | "breakfast"
  | "brunch"
  | "lunch"
  | "dinner"
  | "appetizer"
  | "desert"
  | "cocktail"
  | "soup"
  | "cookie"
  | "chocolate"

export type RecipeTheme =
  | "appetizers"
  | "breakfast"
  | "brunch"
  | "lunch"
  | "dinner"
  | "desserts"
  | "baking"
  | "grilling"
  | "slow cooker/crockpot"
  | "instant pot/pressure cooker"
  | "one-pot meals"
  | "salads"
  | "sandwiches"
  | "soups and stews"
  | "pasta"
  | "rice dishes"
  | "vegetarian/vegan"
  | "gluten-free"
  | "dairy-free"
  | "low-carb"
  | "high-protein"
  | "keto"
  | "paleo"
  | "mediterranean"
  | "asian"
  | "mexican"
  | "italian"
  | "indian"
  | "chinese"
  | "thai"
  | "greek"
  | "middle eastern"
  | "japanese"
  | "french"
  | "american"
  | "bbq"
  | "seafood"
  | "chicken"
  | "beef"
  | "pork"
  | "lamb"
  | "vegetables"
  | "side dishes"
  | "sweets and treats"
  | "smoothies and beverages"
  | "cocktails"
  | "holiday and special occasion"
  | "healthy and light"
  | "comfort food"
  | "fusion and experimental"
