import {
  KitchenToolCategory,
  RecipeDifficulty,
  RecipeTag,
  RecipeTheme,
} from "@/types/recipe"

export const kitchenToolCategory: KitchenToolCategory[] = []

export const recipeDifficulties = [
  "beginner",
  "easy",
  "moderate",
  "hard",
  "expert",
] as const

export const recipeTag: RecipeTag[] = []

export const recipeThemes = [
  "appetizers",
  "breakfast",
  "brunch",
  "lunch",
  "dinner",
  "desserts",
  "baking",
  "grilling",
  "slow cooker/crockpot",
  "instant pot/pressure cooker",
  "one-pot meals",
  "salads",
  "sandwiches",
  "soups and stews",
  "pasta",
  "rice dishes",
  "vegetarian/vegan",
  "gluten-free",
  "dairy-free",
  "low-carb",
  "high-protein",
  "keto",
  "paleo",
  "mediterranean",
  "asian",
  "mexican",
  "italian",
  "indian",
  "chinese",
  "thai",
  "greek",
  "middle eastern",
  "japanese",
  "french",
  "american",
  "bbq",
  "seafood",
  "chicken",
  "beef",
  "pork",
  "lamb",
  "vegetables",
  "side dishes",
  "sweets and treats",
  "smoothies and beverages",
  "cocktails",
  "holiday and special occasion",
  "healthy and light",
  "comfort food",
  "fusion and experimental",
] as const
