import { RecipeTheme } from "@/types/recipe"

type Theme = {
  name: RecipeTheme
}

export const themes: Theme[] = [
  { name: "appetizers" },
  { name: "breakfast" },
  { name: "brunch" },
  { name: "lunch" },
  { name: "dinner" },
  { name: "desserts" },
  { name: "baking" },
  { name: "grilling" },
  { name: "slow cooker/crockpot" },
  { name: "instant pot/pressure cooker" },
  { name: "one-pot meals" },
  { name: "salads" },
  { name: "sandwiches" },
  { name: "soups and stews" },
  { name: "pasta" },
  { name: "rice dishes" },
  { name: "vegetarian/vegan" },
  { name: "gluten-free" },
  { name: "dairy-free" },
  { name: "low-carb" },
  { name: "high-protein" },
  { name: "keto" },
  { name: "paleo" },
  { name: "mediterranean" },
  { name: "asian" },
  { name: "mexican" },
  { name: "italian" },
  { name: "indian" },
  { name: "chinese" },
  { name: "thai" },
  { name: "greek" },
  { name: "middle eastern" },
  { name: "japanese" },
  { name: "french" },
  { name: "american" },
  { name: "bbq" },
  { name: "seafood" },
  { name: "chicken" },
  { name: "beef" },
  { name: "pork" },
  { name: "lamb" },
  { name: "vegetables" },
  { name: "side dishes" },
  { name: "sweets and treats" },
  { name: "smoothies and beverages" },
  { name: "cocktails" },
  { name: "holiday and special occasion" },
  { name: "healthy and light" },
  { name: "comfort food" },
  { name: "fusion and experimental" },
]
