name: Docker Hub Deployment

on:
  push:
    tags:
      # SemVer (https://semver.org/), but prefixed with `v` and only with digits
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  # Push to the GitHub Packages registry
  REGISTRY: ghcr.io
  # Name the Docker image after the GitHub repository
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/homechef:latest .

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/homechef:latest
